id: P856EC16F
initial_creation_type: input
source_metadata:
  title: Yangthang Rinpoche Series
  language: fr
  description: Texts by Domang Yangthang Rinpoche (mdo mang g.yang thang rin po che,
    1929–2016), the renowned incarnation of Domang Dorje Dechen Lingpa (1857–1928).
  volume:
    9b9ee704f2e54ae49f1b420bdcc0a79d:
      title: A Brief Presentation of View, Meditation and Action
      parent: Advice
    933f3c283c3341e289542305cb062b8a:
      title: Prayer for the Flourishing of the Dzogchen Teachings of Sogyal Rinpoche,
        the incarnation of Lerab Lingpa
      parent: Prayers
created_at: '2022-03-01T02:01:26.942295'
last_modified_at: '2022-03-01T02:01:26.942298'
